#!/bin/bash

#Lamp Control Script Version 0.3.5 by Mel McCalla


#Variable Setup
VERSION="0.3.5"

EXITSTATUS=1
VERBOSE="false"


function simpleOnOff ()
{
	for i in `seq -s " " 1 $ITERATIONS`
	do
	{
		on $PIN
		sleep $ONTIME
		off $PIN
		sleep $OFFTIME
	}
	done
}

function setup ()
{
	if [ "$VERBOSE" = "true" ] ; then echo "Changing permissions of /sys/class/gpio/export." ; fi
	sudo chmod 222 /sys/class/gpio/export
	if [ "$VERBOSE" = "true" ] ; then echo "Enabling GPIO pin $PIN." ; fi
	echo $PIN >> /sys/class/gpio/export
	if [ "$VERBOSE" = "true" ] ; then echo "Changing permissions of /sys/class/gpio/gpio$PIN/direction." ; fi
	sudo chmod 666 /sys/class/gpio/gpio$PIN/direction
	if [ "$VERBOSE" = "true" ] ; then echo "Changing permissions of /sys/class/gpio/gpio$PIN/value." ; fi
	sudo chmod 666 /sys/class/gpio/gpio$PIN/value
	if [ "$VERBOSE" = "true" ] ; then echo "Setting GPIO pin $PIN to output." ; fi
	echo out > /sys/class/gpio/gpio$PIN/direction
}
function on ()
{
	echo 1 > /sys/class/gpio/gpio$PIN/value
	if [ "$VERBOSE" = "true" ] ; then echo "ON" ; fi
}

function off ()
{
	echo 0 > /sys/class/gpio/gpio$PIN/value
	if [ "$VERBOSE" = "true" ] ; then echo "OFF" ; fi
}

function usage ()
{
	echo 'Usage:'
	echo '	lampctl ramp|simple|on|off'
	echo '	For more options, run "lampctl -h"'
}

function version ()
{
	echo "Lamp Control Script version $VERSION by Mel McCalla"
}
function arguments ()
{
	case $1 in
		"")
			version
			usage
			exit 1
		;;
		"-h"|"--help")
			case $2 in
				simple)
					echo 'Turns on and off the lamp on a cycle.  '
					echo '	lampctl simple PIN ONTIME OFFTIME ITERATIONS'
					exit 0
				;;
				ramp)
					echo 'Increases or decreases the speed and time the lamp spends flashing.  '
					echo '	lampctl ramp PIN STARTONTIME STARTOFFTIME ENDONTIME ENDOFFTIME ITERATIONS'
					exit 0
				;;
				setup)
					echo 'Initializes a GPIO pin and prepares it for output.  '
					echo '	lampctl setup PIN'
					exit 0
				;;
				on)
					echo 'Turns on the lamp.  '
					echo '	lampctl on PIN'
					exit 0	
				;;
				off)
					echo 'Turns off the lamp.  '
					echo '	lampctl off PIN'
				;;
				*)
					echo "Error: No such mode $2"
					usage
					exit 1
			esac
		;;
		"-V"|"--version")
			version
			exit 0
		;;
		"-v"|"--verbose")
			VERBOSE="true"
			if [ "$2" != "" ]; then
				shift
				arguments $@
			else 
				exit 1
			fi
		;;
		"-*")
			echo "Error:  No such option $1.  "
			usage
		;;
		*)
			while test "$1" != "" ; do
				case $1 in
				"ramp")
					EXITSTATUS="0"
					PIN=$2
					STARTONTIME=$3
					STARTOFFTIME=$4
					STARTITERATIONS=$5
					ENDONTIME=$6
					ENDOFFTIME=$7
					rampOnOff
					shift 7
				;;
				"simple")
					EXITSTATUS="0"
					PIN=$2
					ONTIME=$3
					OFFTIME=$4
					ITERATIONS=$5
					simpleOnOff
					shift 4
				;;
				"setup")
					EXITSTATUS="0"
					PIN=$2
					setup
					exit 0
				;;
				"on")
					EXITSTATUS="0"
					PIN=$2
					on 
					exit 0
				;;
				"off")
					EXITSTATUS="0"
					PIN=$2
					off
					exit 0
				;;
				*)
					echo "Error:  No such mode $1.  "
					usage
					exit 1
				esac
			shift
			done
	esac
}
arguments $@
if [ "$EXITSTATUS" = 1 ]; then
		echo 'An error occurred.  '
fi
exit $EXITSTATUS
